;远程锁机
[RemoteLock]
;是否使能监测网关与公网的连接状态0 - 使能，1 - 不使能
EnableMoniterConnect = 0
;时间（年月日时），用以存储modBus客户端刷过来的时间	
lastTime = (2019,10,31,12)
;累计未连接时间，当通讯连接上时，将改值置为0			
disconnectTotalTime = 0.0000000
;连接类型、连接状态、更新时间的刷新周期（单位小时）
updataInterval = 1
;下发命令状态，下次上电时生效
lastClockSts = 0
;0-公网未下发命令， 1-公网下发命令			
netCommandFlag = 0
;按日期上锁功能，获取的日期			
commandDate = (2019, 10, 31)
;记录按日期下发命令操作的标志，0-无操作，1-解锁中，2-锁机中，3-功能使能中，4-功能关闭中			
dateLockFlag = 0


;跑合测试
[Running]
;跑合测试时间
RunningInTime = 0.561389
;跑合设定时间   
RunningAllTime = 36
;运行总时间       
RunningTime = 0.561389

;OPCUA配置信息
[OPCUAConfig]
;报警状态显示等级
OPCUAConnectErrLevel = 1

[Maintain]
password = 123456
;出厂日期
ProductionDate = (0,0,0)
;维保计时
LastMaintain = (0,0,0)
;下次维保日期
NextMaintain = (0,0,0)
;维保后累计时长
MaintainTime = 0.561389
;建议维保周期
MaintainPeriod = 0.0000000
