;
;ioCfg.ini  系统IO参数配置
;
;io配置
[IO_PARAM]
PhysicDinNum = 32
PhysicDoutNum = 32
PhysicAinNum = 0
PhysicAoutnum = 0
VirtualDinNum = 256
VirtualDoutNum = 256
VirtualAinNum = 128
VirtualAoutnum = 128
DI_deadManBt1 = 1
DI_deadManBt2 = 2
DI_remoteStop = 3
DI_safetyDoor = 4
DI_eStopBt = 5
DI_remoteStart = 6
DI_remoteResetErr = 7
DI_cabMode = 8
DI_remoteLoadProg = 9		
DI_exitCycle = 10
DI_GS = 12
DI_AS = 13
DO_progRun = 1
DO_sysError = 2
DO_tpLinkState = 3
DO_robotMot = 4
DO_eStopBt = 5
DO_trigCam = 6
DO_systemLock = 7
DO_remoteLoadProg =8
DO_mtcEnable =9
DO_DebugMode =10
	
;有效电平 0: 高有效 1:低有效
DI_deadManBt1_P = 0
DI_deadManBt2_P = 0
DI_remoteStop_P = 0
DI_safetyDoor_P = 0
DI_eStopBt_P = 1
DI_remoteStart_P = 0
DI_remoteResetErr_P = 0
DI_cabMode_P = 0
DI_remoteLoadProg_P = 0  
DI_exitCycle_P = 0
DI_GS_P = 1
DI_AS_P = 1

DO_progRun_P = 0
DO_sysError_P = 0
DO_tpLinkState_P = 0
DO_robotMot_P = 0
DO_eStopBt_P = 1
DO_trigCam_P = 0
DO_systemLock_P = 0
DO_remoteLoadProg_P = 0	 
DO_mtcEnable_P = 0 
DO_DebugMode_P = 0
