;
;ioNote.ini  IO注释
;

;DI的注释
[DI]
DI1                     = 手压信号1
DI2                     = 手压信号2
DI3                     = 远程暂停信号
DI4                     = 安全门信号
DI5                     = 急停信号
DI6                     = 远程启动信号
DI7                     = 远程复位信号
DI8                     = 电柜模式信号
DI9                     = 远程重新加载自启动程序信号
DI10                    = 程序PC返回首行信号
DI12_25GenCE            = GS
DI13_25GenCE            = AS
DI12                    = 
DI15                    = 

;DI的英文注释
[DI_ENG]
DI1                     = Deadman switch 1
DI2                     = Deadman switch 2
DI3                     = External pause
DI4                     = Safety door
DI5                     = Emergency stop
DI6                     = External start
DI7                     = External reset
DI8                     = Cabinet mode
DI9                     = External reload auto start program
DI10                    = ProgPC return to the first line
DI12_25GenCE            = GS
DI13_25GenCE            = AS

;D0的注释
[DO]
DO1                     = 程序运行状态
DO2                     = 系统错误状态
DO3                     = 示教器连接状态
DO4                     = 机器人励磁状态
DO5                     = 急停输出状态
DO6                     = 系统预留
DO7                     = 系统锁机状态
DO8                     = 远程重新加载程序完成状态
DO9                     = 系统预留
DO9_BBH	                = 维保模式状态
DO10_25GenCE            = 调试模式状态
DO15                    = 
DO11                    = 
DO10                    = 

;D0的英文注释
[DO_ENG]
DO1                     = Program running
DO2                     = System error
DO3                     = TP connect
DO4                     = Motors on
DO5                     = Emergency stop
DO6                     = System reserved
DO7                     = System lock
DO8                     = External reloaded done
DO9                     = System reserved
DO9_BBH	                = Maintenance mode
DO10_25GenCE            = Debug mode

;AI的注释
[AI]
AI1                     = 



;AO的注释
[AO]
AO1                     = 



;SIMDI的注释
[SIMDI]
SIMDI1 = Communication bit
SIMDI2 = Communication bit
SIMDI3 = Communication bit
SIMDI4 = Communication bit
SIMDI5 = Communication bit
SIMDI6 = Communication bit
SIMDI8 = Communication bit
SIMDI9 = Start
SIMDI10 = Pause
SIMDI11 = Stop
SIMDI12 = Reload autorun prog
SIMDI13 = Reset
SIMDI14 = Set the global speed
SIMDI15 = 
SIMDI16 = 
SIMDI17 = 
SIMDI18 = Enable drives
SIMDI19 = Disable drives
SIMDI20 = Load project
SIMDI21 = Unload project
SIMDI24 = Heartbeat
SIMDI25 = 
SIMDI26 = 
SIMDI27 = 
SIMDI28 = 
SIMDI29 = 
SIMDI30 = 
SIMDI31 = 
SIMDI32 = 
SIMDI33 = 
SIMDI34 = 
SIMDI35 = 
SIMDI36 = 


;SIMDO的注释
[SIMDO]
SIMDO1 = Communication bit
SIMDO2 = Communication bit
SIMDO3 = Communication bit
SIMDO4 = Communication bit
SIMDO5 = Communication bit
SIMDO7 = Communication bit
SIMDO6 = Communication bit
SIMDO8 = Communication bit
SIMDO9 = Program running
SIMDO10 = Program paused
SIMDO12 = Reload successfully
SIMDO11 = Program stopped
SIMDO13 = Robot alarm status
SIMDO14 = OPmode T1
SIMDO15 = OPmode T2
SIMDO16 = OPmode AUTO
SIMDO17 = OPmode REMOTE
SIMDO18 = OPmode NOK
SIMDO19 = Motors ON
SIMDO20 = Robot InMotion
SIMDO21 = Robot OnPath
SIMDO22 = Emergency Stop
SIMDO24 = Heartbeat
SIMDO25 = EC status monitoring
SIMDO26 = PN status monitoring



;SIMAI的注释
[SIMAI]
SIMAI1 = Global speed
SIMAI2 = Project number
SIMAI3 = 



;SIMAO的注释
[SIMAO]
SIMAO1 = Current global speed
SIMAO2 = Current project number
SIMAO3 = 
SIMAO4 = TCP speed
SIMAO5 = Alarm code
SIMAO17 = Current location J1 X
SIMAO18 = Current location J2 Y
SIMAO19 = Current location J3 Z
SIMAO20 = Current location J4 A
SIMAO21 = Current location J5 B
SIMAO22 = Current location J6 C



