;
;运动参数motionCfg.ini
;

;点动及寸动参数
[JOG_PARAM]
JogInAutoMode = 0

;acc time percent
JogAccTimePer = 0.5

;dec time percent
JogDecTimePer = 0.5

;Cart Jog Increment--mm deg
JogMicroIncCartX = 1
JogMicroIncCartY = 1
JogMicroIncCartZ = 1
JogMicroIncCartA = 0.5
JogMicroIncCartB = 0.5
JogMicroIncCartC = 0.5

;Joint Jog Increment--deg
JogMicroIncJointA1 = 0.5
JogMicroIncJointA2 = 0.5
JogMicroIncJointA3 = 0.5
JogMicroIncJointA4 = 0.5
JogMicroIncJointA5 = 0.5
JogMicroIncJointA6 = 0.5
JogMicroIncJointA7 = 0.5
JogMicroIncJointA8 = 0.5
JogMicroIncJointA9 = 0.5
JogMicroIncJointA10 = 0.5
JogMicroIncJointA11 = 0.5
JogMicroIncJointA12 = 0.5
JogMicroIncJointA13 = 0.5
JogMicroIncJointA14 = 0.5
JogMicroIncJointA15 = 0.5
JogMicroIncJointA16 = 0.5

;Jog Increment speed override percent(<=50): 1--1%
JogMicroIncOvrride = 5


;碰撞检测参数
[COLLIDE_DETECT_PARA]
CollideDeteEn           = 1
CollideDeteStopEn       = 1
ThreshVPerc_A1          = 100
ThreshVPerc_A2          = 100
ThreshVPerc_A3          = 100
ThreshVPerc_A4          = 100
ThreshVPerc_A5          = 100
ThreshVPerc_A6          = 100
ThreshVPerc_A7 = 100
ThreshVPerc_A8 = 100
ThreshVPerc_A9 = 100
ThreshVPerc_A10 = 100
ThreshVPerc_A11 = 100
ThreshVPerc_A12 = 100
ThreshVPerc_A13 = 100
ThreshVPerc_A14 = 100
ThreshVPerc_A15 = 100
ThreshVPerc_A16 = 100
ColliFinishIOType       = 0
ColliFinishIOPort       = 0


;振动抑制配置，1为开，0为关
[VIBRA_BATEMENT_PARAM]
VibraBatement = 1
VibraBatemMode_A1 = 0
VibraBatemMode_A2 = 0
VibraBatemMode_A3 = 0
VibraBatemMode_A4 = 0
VibraBatemMode_A5 = 0
VibraBatemMode_A6 = 0
VibraBatemMode_A7 = 0
VibraBatemMode_A8 = 0
VibraBatemMode_A9 = 0
VibraBatemMode_A10 = 0
VibraBatemMode_A11 = 0
VibraBatemMode_A12 = 0
VibraBatemMode_A13 = 0
VibraBatemMode_A14 = 0
VibraBatemMode_A15 = 0
VibraBatemMode_A16 = 0

;系统默认的tool,usercoord,payload参数
[SYS_PARAM]
DefaultToolName = nullTool
DefaultToolScope = 0
DefaultUserCoordName = World
DefaultUserCoorScope = 0
DefaultPayloadName      = PAYLOAD1
DefaultPayloadScope     = 1
StandEnableSts          = 0
StandWaitTime           = 60.000000

;传送带参数
[CONVEYER_PARAM]

;方向
direction = 1

;分辨率     
resolution = 0

;减速比分子、分母     
molecule = 0
denominator = 0

;当量       
equivalent = 0


;跟随参数
[TRACK_PARAM]

;类型 0:Axis,1:cart
trackType = 0

;左边界、右边界、最后抓取位置、工件高度
left = -150
right = 150
latestPos = 150
height = 2

;x方向补偿量
compensation = 0

;跟随速度、加速度、加加速度
speed = 0.5
acceleration = 0.5
jerk = 1

;跟随精度、精度等级1:high,2:normal,3:low
accuracy = 2
level = 2

;相机触发时间(ms)
triggleTime = 1000
