;
;multi-StationCfg.ini  系统参数配置
;
;系统版本信息

[config]
isEnable                = 1

[station1]
enableSts               = 1
startInput              = 11
stopInput               = 12
startOutput             = 11
stopOutput              = 12
project                 = aaa
program                 = st1

[station2]
enableSts               = 1
startInput              = 13
stopInput               = 14
startOutput             = 13
stopOutput              = 14
project                 = aaa
program                 = st2

[station3]
enableSts               = 0
startInput              = 0
stopInput               = 0
startOutput             = 0
stopOutput              = 0
project                 = 
program                 = 

[station4]
enableSts               = 0
startInput              = 0
stopInput               = 0
startOutput             = 0
stopOutput              = 0
project                 = 
program                 = 
