;
;机器人参数robotCfg.ini
;

[ROBOT_PARA]
;本体、电柜、cpu序列号
RobSN = V.2021T22
CabinetSN = V.2021T22
CPUSN = V.2021T22

;用户自定义机器人名称Id
UserDefRobId            = estunrobot

;机器人类型
RobotType               = ER35B_1810_A6
RobotTypeList =  ER6_1450_A6|ER6_A6|ER8_1450_HW_A6|ER8_1500_CW_A6|ER8_2000_CW_S_A6|ER8_2000_HW_S_A6|ER8_2000_HW_T_A6|ER10B_900_MI_HI_A6|ER12_A6|ER12_H5_A6|ER12B_A6|ER16_A6|ER20_1745_PV_A6|ER20_1780_A6|ER20_1780_DC_A6|ER20_1780_HI_A6|ER20_2000_HI_A6|ER20_2300_HI_A6|ER20B_2010_HI_A6|ER30_A6|ER30_DC_A6|ER35_A6|ER35B_1810_A6|ER45_A6|ER50_A6|ER50_DC_A6|ER50B_A6|ER50B_DC_A6|ER70_A6|ER80_A6|ER80B_A6|ER100_3500_A6|ER100_A6|ER130_3200_A6|ER130_A6|ER170_A6|ER220_3200_A6|ER220_A6|ER270_2850_A6|ER280_A6|ER350_A6|ER350_H5_A6|ER500_A6|ER600_A6|ER500_H5_A6|ERC6_A6|ERC7_910_A6|ERC8_720_A6|ERC8_1200_A6|ERC10_A3|ERC10_A4|ERC10_A6|ERC10_T_A6|Pallet15|Pallet60|Pallet120|Pallet180|QRC_405_ECO_S_A6|QRH_295_ECO_A6|QRH_405_ECO_S_A6|QRH_405_ECO_T_A6|SCARA400S|SCARA500S|SCARA500S_3|SCARA500S_10|SCARA550S|SCARA600S|SCARA600S_10|SCARA700S|SCARA700S_10|SCARA800S|SCARA800S_10|SCARA800S_HI|SCARA1000S|SCARA1000S_HI|SCARA1200S_50

;安装方式；0-正装Floor；1-吊装Ceiling （重启有效）
[MOUNT_PARAM]
MountMethod = 0

;零位单圈值参数
[AXIS_SINGLE_VALUE]
AxisSingleV_A1          = 7928833
AxisSingleV_A2          = 7345722
AxisSingleV_A3          = 8231153
AxisSingleV_A4          = 4188113
AxisSingleV_A5          = 5939225
AxisSingleV_A6          = 430452
AxisSingleV_A7 = 0
AxisSingleV_A8 = 0
AxisSingleV_A9 = 0
AxisSingleV_A10 = 0
AxisSingleV_A11 = 0
AxisSingleV_A12 = 0
AxisSingleV_A13 = 0
AxisSingleV_A14 = 0
AxisSingleV_A15 = 0
AxisSingleV_A16 = 0

;多机协同组使能状态参数
[MULTIROBOT_PARAM]
MSGroupId               = 0
MSGroupEnSts[0][0]      = 0
MSGroupEnSts[0][1]      = 0
MSGroupEnSts[0][2]      = 0
MSGroupEnSts[0][3]      = 0
MSGroupEnSts[0][4]      = 0
MSGroupEnSts[0][5]      = 0
MSGroupEnSts[0][6]      = 0
MSGroupEnSts[1][0]      = 0
MSGroupEnSts[1][1]      = 0
MSGroupEnSts[1][2]      = 0
MSGroupEnSts[1][3]      = 0
MSGroupEnSts[1][4]      = 0
MSGroupEnSts[1][5]      = 0
MSGroupEnSts[1][6]      = 0
MSGroupEnSts[2][0]      = 0
MSGroupEnSts[2][1]      = 0
MSGroupEnSts[2][2]      = 0
MSGroupEnSts[2][3]      = 0
MSGroupEnSts[2][4]      = 0
MSGroupEnSts[2][5]      = 0
MSGroupEnSts[2][6]      = 0
