;
;systemCfg.ini  系统参数配置
;
;系统参数
[SYS_PARAM]
;暂停再启动时弹出与否
ContinueDisplayDlgEnable = 1
;手动自动模式下网络检测使能
CheckNetworkEnable = 1
;指令中变量域显示 0:默认不显示 1:显示G:
DisplayVarScope = 1
;断电记忆程序指针行号功能(0:不启用，1：启用)
MemProgPCEnable         = 0
;安全门信号停机方式配置功能(0：暂停且不下励磁、1：暂停且下励磁、2：急停且下励磁)
SafeDoorMode            = 1
;长按复位IO（超过5s)，则重新加载自启动工程和程序功能 类似，系统IO-9的功能(0:不启用，1启用)
ResetSigAutoLoadProg	= 0




;系统IP参数
SetSysIPFlag            =0
ControllerIP =192.168.6.63
ControllerPort = 56176
RTOSIP =192.168.6.68
RTOSPort = 56177
RTOSCommIP =192.168.6.69
LAN4IP                  = 192.168.1.63
LAN4IPNetmask           = 255.255.255.0
LAN4IPGateway           = 192.168.60.1
RTOS2IP                 = 192.168.60.68
RTOS2IPNetmask          = 255.255.255.0
RTOS2IPGateway          = 192.168.60.200
;视觉参数: 设备类型DeviceType：1：2D, 2:3D  视觉类型Visiontype：0：静态  1：动态
DeviceType = 2
VisionIP = 192.168.6.230
VisionPort = 5000
VisionType = 0
;remote monitor control参数
IpAddrStr = 127.0.0.1
listenPort = 1502
registLen = 2500
connectDelay = 2500
stringLen = 8
TestOverallspeed = 90
RobotTestTime = 72
TorqueAlarm1 = 100
TorqueAlarm2 = 100
TorqueAlarm3 = 100
TorqueAlarm4 = 100
TorqueAlarm5 = 100
TorqueAlarm6 = 100
MultiLineParseEnable    = 0
ParseLevel              = 0
TrigStepEnable          = 0
MultiLineParseMaxExecCount = 5
MultiLineParseDelayTime = 20
;modbusTcpCtrl参数
[MBTCPCtrl_PARAM]
listenPort = 502
registLen = 1500
timeout = 20000
cmdexe_timeout = 2000
[VIRTUAL_TEST]
VirtualOpen = 0
TcpPort = 56111
SendCycle = 4

[LogFunctions_cfg]
IsBackMotionInError = 1
