;系统版本信息

[VERSION_INFO]
RS_VERSION = RCS2 V1.35.04
ERC_VERSION = V1.35.C05.R3
PLC_VERSION = V0.0.25
APPSOFT_TYPE = BASIC
APPSOFT_TYPE_LIST = BASIC
APPSOFT_VERSION = V0.0.0
DEVELOPERS = ESTUN ROBOTICS
DEVELOPDATE = 2025.08.11
INSTPARSE_VERSION = V1.02
